# Generated by Django 2.1 on 2018-08-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_team_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDesc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='user', max_length=200)),
                ('desc', models.CharField(default='desc', max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='zayavki',
            field=models.CharField(default='desc', max_length=10000),
        ),
    ]
