# Generated by Django 2.1 on 2018-08-27 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180827_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='zayavki',
            field=models.CharField(default='Пока заявок нет, ', max_length=10000),
        ),
    ]
