# Generated by Django 2.1 on 2018-08-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20180827_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdesc',
            name='desc',
            field=models.CharField(default='Пока заявок нет, ', max_length=10000),
        ),
    ]
