# Generated by Django 2.1 on 2018-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180827_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zayavki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(default='teamname', max_length=200)),
                ('zayavki', models.CharField(default='Пока заявок нет', max_length=10000)),
            ],
        ),
        migrations.RemoveField(
            model_name='team',
            name='zayavki',
        ),
    ]
