# Generated by Django 2.1 on 2018-08-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_team_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='telegram',
            field=models.CharField(default='telega', max_length=500),
        ),
    ]
