# Generated by Django 2.1 on 2018-08-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180820_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='person',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
